{% set name = "pyvers" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vmoens/pyvers/archive/v{{ version }}.tar.gz
  sha256: 8da0cc90029bd57f172625e3c1a634ff93206df17d60b0dfd10c8c9d3254751a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - packaging >=25.0,<26.0

test:
  imports:
    - pyvers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vmoens/pyvers
  summary: A Python library for managing multiple versions of dependencies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
