schema_version: 1

context:
  name: pyvers
  version: "0.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/vmoens/pyvers/archive/v${{ version }}.tar.gz
  sha256: 4bdbc687f3f12ad9b38e4f7116d39a23e43cfbf2d15b8c767b040b712e8ff0fc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pyvers
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: A Python library for managing multiple versions of dependencies
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/vmoens/pyvers

extra:
  recipe-maintainers:
    - jan-janssen
